### PR TITLE
trunk sync up to 11748 for emu 800

### PR DESCRIPTION
**Pull request by WXbet**
- revert icam V9
- remove ffdecsa and switch to libdvbcsa
- remove emu streamrelay server
- use libdvbcsa in module-emulator-powervu
- increase the EMU version number to 800

This PR might be a good base for you @oscam-emu.

### CODE REVIEW

**Comment by oscam-emu** [comment]
@WXbet I merged svn, but there are some parts that I missed, so I will add them and force push master branch soon.

**Comment by oscam-emu** [comment]
@WXbet I give up.... I am unable to track what's changed and modify accordingly.

If you are capable of providing a proper PR against https://github.com/oscam-emu/oscam-patched/tree/99c4631a73e3da426a6d31557f64fef610de183d with correct merging of oscam-svn branch (while keeping original hashes like I did) with additional changes needed to the emu part resolving merge conflicts, go ahead.

Any additional changes like emu optimizations or compiler warning fixes should be on separate commits.

**Comment by WXbet** [comment]
As I can see your oscam-svn merge is done with the  correct hashes. What's left are the oscam-emu changes to work with libdvbsca or?

**Comment by oscam-emu** [comment]
More or less I have added the additional changes needed for emu to work with libdvbcsa etc. but I have missed changes [like this in line 27](https://github.com/oscam-emu/oscam-patched/pull/114/files#diff-fe7a0ba4d44a04d112389d9b2c851c39161f99b3b1efc7e9d621a69d121921fdR27) which are not part of the trunk.

Generally can't understand why people still insist of using svn nowadays. It would be much easier if they had switched to git

**Comment by WXbet** [comment]
@oscam-emu: Please look here: https://github.com/oscam-emu/oscam-patched/pull/115

**Comment by oscam-emu** [comment]
thanks, resovled

**Comment by AbuBaniaz** [comment]
While the iron is hot, can we look at this please?
oscam-emu/oscam-patched/pull/110

**Comment by WXbet** [comment]
We need this changes on oscam-trunk now. Maybe @ohmza can review this changes.

**Comment by oscam-emu** [comment]
this should be added to trunk, since streamserver is there now, correct?

**Comment by ohmza** [comment]
@AbuBaniaz Please check your PM on digitalworldz. If you can confirm that the patch I just sent it to you is working, I will send it to Streamboard moderator.

**Comment by oscam-emu** [comment]
Guys the patch is automatically created via github actions and should be perfect. See: https://github.com/oscam-emu/oscam-emu

**Comment by oscam-emu** [comment]
You only need to care for this repo at the moment.

I have setup one github action that pulls from streamboard every 12 hours and updates this repo's oscam-svn branch. This branch should NOT be edited at all.

When new commits are pulled from streamboard, it's a matter of manually merging the oscam-svn branch into the master branch and resolving any conflicts like we did yesterday.

After a new commit is done in the master branch of this repo, a github action updates the patch on the original oscam-emu repo. So nothing to do for that. It's set and forget for a long time now

**Pull request closed without merging**
