### PR TITLE
Travis CI support

### PR DESCRIPTION
**Pull request by persianpros**

### CODE REVIEW

**Comment by oscam-emu** [comment]
Thanks. It was in my to do list to add a travis script. Is that all that is needed?

What about building for various STBs that need specific code to be enabled (such as STAPI, AZBOX, COOLAPI) and a special compiler/toolchain. Is is possible to check them too?

**Comment by persianpros** [comment]
It's possible but it's really hard so I don't recommend it, just merge this PR then enable Travis CI you're good to go.

If any project wants to check all possible build systems it's going to be next World War :D

**Comment by persianpros** [comment]
Ok now you need to enable Travis CI for this repo just login with your github account to https://travis-ci.org/account/repositories

**Comment by oscam-emu** [comment]
I've already done this, I just need to make some commits to see how it works.

**Pull request merged**
