### PR TITLE
Fix sync workflow to properly push commits

### PR DESCRIPTION
**Pull request by WXbet**

### CODE REVIEW

**Comment by nautilus7** [comment]
Fixes #6

**Comment by WXbet** [comment]
Can you please merge the changes to master branch? Seems I dont have write access.

**Comment by nautilus7** [comment]
I thought I fixed write the day before yesterday... Argh...

**Comment by WXbet** [comment]
Ah okay. I'll check it, wait. How to avoid this Mege Commit?
image

**Comment by nautilus7** [comment]
Either with merge commit, or with rebase. I don't care.

Rebase is cleaner, but merge commit maybe heps better distinguish between oscam commits and emu only commits.

**Comment by WXbet** [comment]
Rebase did the job fine :-)

**Comment by nautilus7** [comment]
No it didn't.... My fault. Should have thought better before saying that.

**Comment by nautilus7** [comment]
I'll reset and make merge commit. Sorry

**Comment by WXbet** [comment]
Okay thank you. Merge is our way!

**Pull request merged**
