### PR TITLE
Add readme.md file with build status badge

### PR DESCRIPTION
**Pull request by nautilus7**

### CODE REVIEW

**Comment by nautilus7** [comment]
Is this enough? I don't want to duplicate the whole plain README file and have to sync manually when is changed. Thoughts?

**Comment by AbuBaniaz** [comment]
Why not convert the existing readme file? Isn't it just capitals and .md file extension?

**Comment by AbuBaniaz** [comment]
On second thoughts, I think conversion of plain text file to markdown version should be done upstream.

**Comment by WXbet** [comment]
https://github.com/oscam-emu/oscam-patched/commit/dd929d25a7ab8b2b654b0e6ffc61c5a1cb81e607

**Pull request closed without merging**
