### PR TITLE
Update sync-gitlab.yml

### PR DESCRIPTION
**Pull request by WXbet**
- both commands can be reduced to one command because oscam-gitlab creates annotated tags in automation
- maybe we can automerge from oscam-gitlab branch

### CODE REVIEW

**Comment by nautilus7** [comment]
What if there are merge conflicts when merging gitlab to master?

Best would be to create a PR instead. There is a [create pull request action](https://github.com/marketplace/actions/create-pull-request) but haven't look into it.

**Comment by WXbet** [comment]
Not a problem. When merge conflict arise, when we have to do it manually like today. Mostly changes are mergeable.

BUT: my last commit is shitty 👎

**Comment by nautilus7** [comment]
Plus the merge or create PR workflow should be a different workflow in a separate file. Triggered on push in "oscam-gitlab"

**Comment by nautilus7** [comment]
> Not a problem. When merge conflict arise, then we have to do it manually like today. Mostly changes are mergeable.
> 
> BUT: my last commit is shitty 👎

The merge won't happen you mean? Then the action will fail? What do you mean?

**Comment by WXbet** [comment]
> The merge won't happen you mean? Then the action will fail? What do you mean?

Yes, When merge conflict arise, the merge won't happen and the job will fail. The we have to do it by hand.

**Comment by WXbet** [comment]
> Plus the merge or create PR workflow should be a different workflow in a separate file. Triggered on push in "oscam-gitlab"

https://github.com/oscam-emu/oscam-patched/pull/19/commits/bc978e0a9cac17a9d78514d02f37ae94a7b4b456

**Comment by nautilus7** [comment]
@WXbet this ready for merging right?

**Comment by WXbet** [comment]
I think so, not tested if it works fine. It's my first github workflow that I've created so far...

**Pull request merged**
