### PR TITLE
[emu] Fix build warnings

### PR DESCRIPTION
**Pull request by WXbet**

### CODE REVIEW

**Comment by nautilus7** [comment]
Wny not on gitlab?

**Comment by nautilus7** [comment]
Yes, I understand, but it's one more code change introduced by emu that could potentially result in a future merge conflict. Adding that change to oscam, would not have any impact there.

That's my philosophy.

**Comment by WXbet** [comment]
I know your philosophy. 💯 
On the other hand, the upstream cannot manage all things related to oscam-patched. This particular Cccam matter is currently under investigation. There seems to be a regression that is difficult to find. So I stripped down the change on upstream and applied the oscam-patched related change here. 

Btw, I was thinking about my last commit from today at upstream (CS_VERSION injection on build) whether that is the right repo, if I'm honest that just needs  oscam-patched at the moment.

My wish is to move (unused) EMU code that currently exists upstream to oscam-patched. This makes oscam cleaner and the EMU code is in the right place. What do you think about it?

**Comment by nautilus7** [comment]
> I know your philosophy. 💯 On the other hand, the upstream cannot manage all things related to oscam-patched. This particular Cccam matter is currently under investigation. There seems to be a regression that is difficult to fin
> Btw, I was thinking about my last commit from today at upstream (CS_VERSION injection on build) whether that is the right repo, if I'm honest that just needs oscam-patched at the moment.
> 
Not sure I understand, as I haven't closely followed the progress with the versioning changes upstream. Can you explain?

> My wish is to move (unused) EMU code that currently exists upstream to oscam-patched. This makes oscam cleaner and the EMU code is in the right place. What do you think about it?
>
I will have an opinion when I know which code parts you mean.

**Comment by WXbet** [comment]
> versioning changes upstream. Can you explain?

Decision was made by the oscam responsibles, my translated explanation you can find here: https://git.streamboard.tv/common/oscam/-/merge_requests/18

> I will have an opinion when I know which code parts you mean.

Yeah, I have to prepare a list. There are WITH_EMU prepocessor switches, some pvu code and so on.

**Comment by AbuBaniaz** [comment]
Would have been better/simpler to just have a date followed by revision number.

**Comment by nautilus7** [comment]
I have seen the version changes. I meant to explain, what changes are needed for emu.

All with_emu code was added to oscam by gorgone to ease code maintenance and reduce conflicts for this repo here...

Do as you like

**Comment by nautilus7** [comment]
> Would have been better/simpler to just have a date followed by revision number.

I don't see the point in having both revision (an svn leftover) and a version number. But it is what it is.

**Comment by WXbet** [comment]
I think this things could be moved over, not tested yet and maybe incomplete (but the most parts)
[emu_removal.patch](https://github.com/oscam-emu/oscam-patched/files/15144070/emu_removal.patch)

I don't know how to handle the powervu parts: https://git.streamboard.tv/search?search=powervu&nav_source=navbar&project_id=11&group_id=2231&search_code=true&repository_ref=master

> Do as you like
I'll do nothing without your confirmation my friend ;-)
We should do it together then.

**Comment by WXbet** [comment]
> I meant to explain, what changes are needed for emu.

I think emu is fine now, This change make it working for emu as before: https://git.streamboard.tv/common/oscam/-/commit/0f738d2610c6e2d2029af555774c79c3d899adc4
The EMU_VERSION is simply appended to CS_VERSION during build.

**Pull request merged**
